#!/bin/bash
#
# GENESIS 2.0 Mobile - Setup Script
# Run this script to configure your development environment
#

set -e

echo "╔══════════════════════════════════════════════════════════════╗"
echo "║           GENESIS 2.0 Mobile - Setup Script                  ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# Check Node.js version
echo -e "${CYAN}[1/6] Checking Node.js...${NC}"
if command -v node &> /dev/null; then
    NODE_VERSION=$(node -v | cut -d'v' -f2 | cut -d'.' -f1)
    if [ "$NODE_VERSION" -ge 20 ]; then
        echo -e "${GREEN}✓ Node.js v$(node -v) installed${NC}"
    else
        echo -e "${RED}✗ Node.js 20+ required. Current: $(node -v)${NC}"
        echo "  Install with: nvm install 20 && nvm use 20"
        exit 1
    fi
else
    echo -e "${RED}✗ Node.js not found${NC}"
    echo "  Install from: https://nodejs.org/ or use nvm"
    exit 1
fi

# Check Expo CLI
echo -e "${CYAN}[2/6] Checking Expo CLI...${NC}"
if command -v expo &> /dev/null; then
    echo -e "${GREEN}✓ Expo CLI installed${NC}"
else
    echo -e "${YELLOW}Installing Expo CLI...${NC}"
    npm install -g expo-cli eas-cli
    echo -e "${GREEN}✓ Expo CLI installed${NC}"
fi

# Install dependencies
echo -e "${CYAN}[3/6] Installing dependencies...${NC}"
if [ ! -d "node_modules" ]; then
    npm install --legacy-peer-deps
    echo -e "${GREEN}✓ Dependencies installed${NC}"
else
    echo -e "${GREEN}✓ Dependencies already installed${NC}"
fi

# Create .env file
echo -e "${CYAN}[4/6] Configuring environment...${NC}"
if [ ! -f ".env" ]; then
    # Detect local IP for physical device testing
    LOCAL_IP=$(ifconfig 2>/dev/null | grep "inet " | grep -v 127.0.0.1 | head -1 | awk '{print $2}')
    if [ -z "$LOCAL_IP" ]; then
        LOCAL_IP=$(ip addr show 2>/dev/null | grep "inet " | grep -v 127.0.0.1 | head -1 | awk '{print $2}' | cut -d'/' -f1)
    fi
    if [ -z "$LOCAL_IP" ]; then
        LOCAL_IP="localhost"
    fi

    echo "# GENESIS 2.0 Mobile Environment" > .env
    echo "# Generated by setup.sh on $(date)" >> .env
    echo "" >> .env
    echo "# Use localhost for iOS Simulator:" >> .env
    echo "EXPO_PUBLIC_API_URL=http://localhost:8080" >> .env
    echo "" >> .env
    echo "# Use this IP for physical iPhone (same WiFi):" >> .env
    echo "# EXPO_PUBLIC_API_URL=http://${LOCAL_IP}:8080" >> .env
    echo "" >> .env
    echo "# Feature flags" >> .env
    echo "EXPO_PUBLIC_ENABLE_BIOMETRICS=true" >> .env
    echo "EXPO_PUBLIC_ENABLE_NFC=true" >> .env
    echo "EXPO_PUBLIC_ENABLE_PUSH_NOTIFICATIONS=true" >> .env
    echo "EXPO_PUBLIC_ENABLE_AI_CHAT=true" >> .env

    echo -e "${GREEN}✓ Created .env file${NC}"
    echo -e "  ${YELLOW}Your local IP: ${LOCAL_IP}${NC}"
    echo -e "  Edit .env to switch between simulator/physical device"
else
    echo -e "${GREEN}✓ .env file exists${NC}"
fi

# Create asset directories
echo -e "${CYAN}[5/6] Creating asset directories...${NC}"
mkdir -p src/assets/fonts
mkdir -p src/assets/images
mkdir -p src/assets/sounds

# Create placeholder files if they don't exist
if [ ! -f "src/assets/images/icon.png" ]; then
    # Create a simple 1x1 transparent PNG as placeholder
    echo -e "${YELLOW}Creating placeholder images...${NC}"
    # Base64 of a 1x1 transparent PNG
    echo "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==" | base64 -d > src/assets/images/icon.png 2>/dev/null || touch src/assets/images/icon.png
    cp src/assets/images/icon.png src/assets/images/splash.png 2>/dev/null || touch src/assets/images/splash.png
    cp src/assets/images/icon.png src/assets/images/adaptive-icon.png 2>/dev/null || touch src/assets/images/adaptive-icon.png
    cp src/assets/images/icon.png src/assets/images/favicon.png 2>/dev/null || touch src/assets/images/favicon.png
    cp src/assets/images/icon.png src/assets/images/notification-icon.png 2>/dev/null || touch src/assets/images/notification-icon.png
fi
echo -e "${GREEN}✓ Asset directories ready${NC}"

# Download fonts (or create instructions)
echo -e "${CYAN}[6/6] Checking fonts...${NC}"
FONTS_DIR="src/assets/fonts"
if [ ! -f "$FONTS_DIR/Orbitron-Regular.ttf" ]; then
    echo -e "${YELLOW}Fonts not found. Creating fallback configuration...${NC}"

    # Create a fonts readme
    cat > "$FONTS_DIR/README.md" << 'FONTREADME'
# Required Fonts

Download these fonts from Google Fonts and place the .ttf files here:

## Orbitron (Display font)
https://fonts.google.com/specimen/Orbitron
- Orbitron-Regular.ttf
- Orbitron-Bold.ttf
- Orbitron-Black.ttf

## Rajdhani (Body font)
https://fonts.google.com/specimen/Rajdhani
- Rajdhani-Regular.ttf
- Rajdhani-Medium.ttf
- Rajdhani-SemiBold.ttf
- Rajdhani-Bold.ttf

## Share Tech Mono (Code font)
https://fonts.google.com/specimen/Share+Tech+Mono
- ShareTechMono-Regular.ttf

## Quick Download Script
```bash
# Install gdown if not available
pip install gdown

# Or download manually from Google Fonts
```

## Temporary Workaround
The app will use system fonts if these are not available.
Edit src/theme/typography.ts to use 'System' as fallback.
FONTREADME

    echo -e "${YELLOW}  → Download fonts from Google Fonts${NC}"
    echo -e "${YELLOW}  → See: src/assets/fonts/README.md${NC}"
else
    echo -e "${GREEN}✓ Fonts installed${NC}"
fi

echo ""
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║                    Setup Complete!                           ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""
echo -e "${GREEN}Next steps:${NC}"
echo ""
echo "1. Start the GENESIS backend:"
echo -e "   ${CYAN}cd ../caput-ultimate-edition && npm start${NC}"
echo ""
echo "2. Start the mobile app:"
echo -e "   ${CYAN}npm start${NC}"
echo ""
echo "3. Open on device:"
echo "   • Press 'i' for iOS Simulator"
echo "   • Scan QR code with iPhone Camera (requires Expo Go app)"
echo ""
echo "4. For physical iPhone, edit .env to use your IP:"
echo -e "   ${CYAN}EXPO_PUBLIC_API_URL=http://YOUR_IP:8080${NC}"
echo ""
echo -e "${YELLOW}Note: Download custom fonts for the full cyberpunk experience!${NC}"
echo "      See: src/assets/fonts/README.md"
echo ""
