#!/usr/bin/env node
// ═══════════════════════════════════════════════════════════════════════════
// GENESIS 2.0 — First-run setup script
// ═══════════════════════════════════════════════════════════════════════════
// Run: npm run setup
//   or: node scripts/setup.js
//
// Creates directories, generates .env if missing, generates JWT secret.
// Safe to run multiple times — skips anything that already exists.
// ═══════════════════════════════════════════════════════════════════════════

const fs = require("fs");
const path = require("path");
const crypto = require("crypto");

const ROOT = path.resolve(__dirname, "..");
const DATA_DIRS = [
  "data",
  "data/keys",
  "data/audit",
  "data/evidence",
];

// ── Helpers ──────────────────────────────────────────────────────────────

function log(msg) { console.log(`[GENESIS SETUP] ${msg}`); }
function ok(msg) { console.log(`[GENESIS SETUP] ✓ ${msg}`); }
function skip(msg) { console.log(`[GENESIS SETUP] — ${msg} (already exists)`); }

// ── 1. Create data directories ──────────────────────────────────────────

log("Creating data directories...");
for (const dir of DATA_DIRS) {
  const full = path.join(ROOT, dir);
  if (!fs.existsSync(full)) {
    fs.mkdirSync(full, { recursive: true });
    ok(`Created ${dir}/`);
  } else {
    skip(dir);
  }
}

// ── 2. Generate .env if missing ─────────────────────────────────────────

const envPath = path.join(ROOT, ".env");
if (!fs.existsSync(envPath)) {
  log("Generating .env with fresh JWT secret...");
  const secret = crypto.randomBytes(32).toString("hex");
  const envContent = [
    "# GENESIS 2.0 — Environment (auto-generated by npm run setup)",
    "",
    "# Required",
    `GENESIS_JWT_SECRET=${secret}`,
    "",
    "# Directories",
    "GENESIS_KEY_DIR=./data/keys",
    "GENESIS_AUDIT_DIR=./data/audit",
    "GENESIS_EVIDENCE_DIR=./data/evidence",
    "GENESIS_STATIC_DIR=./static",
    "",
    "# Server",
    "GENESIS_PDP_PORT=8080",
    "GENESIS_OWNER_ID=owner",
    "",
    "# AI (optional — uncomment and add your key to enable AI features)",
    "# GENESIS_AI_API_KEY=sk-...",
    "# GENESIS_AI_BASE_URL=https://api.openai.com/v1",
    "",
  ].join("\n");
  fs.writeFileSync(envPath, envContent, "utf-8");
  ok(`Created .env with JWT secret (${secret.slice(0, 8)}...)`);
} else {
  skip(".env");
}

// ── 3. Verify Node version ──────────────────────────────────────────────

const [major] = process.versions.node.split(".").map(Number);
if (major < 20) {
  console.warn(`[GENESIS SETUP] ⚠ Node ${process.versions.node} detected. Node 20+ recommended.`);
} else {
  ok(`Node ${process.versions.node}`);
}

// ── 4. Summary ──────────────────────────────────────────────────────────

console.log("");
console.log("═══════════════════════════════════════════════════════════");
console.log("  GENESIS 2.0 — Ready");
console.log("═══════════════════════════════════════════════════════════");
console.log("");
console.log("  Quick start:");
console.log("");
console.log("    source .env              # load environment");
console.log("    npm start                # launch server on :8080");
console.log("    npm run dev              # launch with hot reload");
console.log("    npm test                 # run tests");
console.log("    npm run gate -- health   # CLI health check");
console.log("");
console.log("  Dashboard:  http://localhost:8080/");
console.log("");
console.log("═══════════════════════════════════════════════════════════");
