name: 'Workflow Guardian'
description: 'Self-Adaptive CI/CD Security Scanner - MAPE-K powered workflow risk detection'
author: 'WorkflowGuardian'

branding:
  icon: 'shield'
  color: 'blue'

inputs:
  path:
    description: 'Path to scan (file or directory)'
    required: false
    default: '.github/workflows'
  confidence-threshold:
    description: 'Minimum confidence to act on findings (0.0-1.0)'
    required: false
    default: '0.75'
  block-threshold:
    description: 'Risk score threshold to block (0-100)'
    required: false
    default: '80'
  warn-threshold:
    description: 'Risk score threshold to warn (0-100)'
    required: false
    default: '30'
  strict:
    description: 'Fail on warnings (not just blocks)'
    required: false
    default: 'false'
  output-format:
    description: 'Output format: text, json, or sarif'
    required: false
    default: 'text'

outputs:
  verdict:
    description: 'Overall verdict: BLOCK, WARN, or ALLOW'
    value: ${{ steps.scan.outputs.verdict }}
  risk-score:
    description: 'Highest risk score found'
    value: ${{ steps.scan.outputs.risk_score }}
  findings-count:
    description: 'Number of findings'
    value: ${{ steps.scan.outputs.findings_count }}
  report:
    description: 'Full scan report (JSON)'
    value: ${{ steps.scan.outputs.report }}

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      shell: bash
      working-directory: ${{ github.action_path }}
      run: npm ci

    - name: Build scanner
      shell: bash
      working-directory: ${{ github.action_path }}
      run: npm run build
      env:
        NODE_ENV: production

    - name: Run Workflow Guardian
      id: scan
      shell: bash
      env:
        GUARDIAN_CONFIDENCE: ${{ inputs.confidence-threshold }}
        GUARDIAN_BLOCK_THRESHOLD: ${{ inputs.block-threshold }}
        GUARDIAN_WARN_THRESHOLD: ${{ inputs.warn-threshold }}
        GUARDIAN_PATH: ${{ inputs.path }}
        GUARDIAN_FORMAT: ${{ inputs.output-format }}
        GUARDIAN_STRICT: ${{ inputs.strict }}
        GUARDIAN_ACTION_PATH: ${{ github.action_path }}
      run: |
        set +e

        # Build arguments safely using environment variables (not shell interpolation)
        ARGS="$GUARDIAN_PATH"
        if [ "$GUARDIAN_FORMAT" = "json" ]; then
          ARGS="$ARGS --json"
        fi
        if [ "$GUARDIAN_STRICT" = "true" ]; then
          ARGS="$ARGS --strict"
        fi

        # Quote paths properly to handle spaces
        OUTPUT=$(node "$GUARDIAN_ACTION_PATH/dist/index.js" scan $ARGS 2>&1)
        EXIT_CODE=$?

        echo "$OUTPUT"

        # Parse results for outputs using heredoc with unique delimiter
        if [ "$GUARDIAN_FORMAT" = "json" ]; then
          # Use unique EOF delimiter to prevent injection
          DELIMITER="EOF_$(date +%s)_$$"
          {
            echo "report<<$DELIMITER"
            echo "$OUTPUT"
            echo "$DELIMITER"
          } >> "$GITHUB_OUTPUT"

          VERDICT=$(echo "$OUTPUT" | jq -r '.[0].verdict // "ALLOW"' 2>/dev/null || echo "ALLOW")
          RISK_SCORE=$(echo "$OUTPUT" | jq -r '[.[].riskScore] | max // 0' 2>/dev/null || echo "0")
          FINDINGS=$(echo "$OUTPUT" | jq -r '[.[].details | length] | add // 0' 2>/dev/null || echo "0")
        else
          VERDICT="ALLOW"
          [ $EXIT_CODE -eq 1 ] && VERDICT="WARN"
          [ $EXIT_CODE -eq 2 ] && VERDICT="BLOCK"
          RISK_SCORE="N/A"
          FINDINGS="N/A"
        fi

        echo "verdict=$VERDICT" >> "$GITHUB_OUTPUT"
        echo "risk_score=$RISK_SCORE" >> "$GITHUB_OUTPUT"
        echo "findings_count=$FINDINGS" >> "$GITHUB_OUTPUT"

        exit $EXIT_CODE

    - name: Create annotations
      if: always()
      shell: bash
      run: |
        if [ "${{ steps.scan.outputs.verdict }}" = "BLOCK" ]; then
          echo "::error::Workflow Guardian: BLOCKED - Critical security issues detected"
        elif [ "${{ steps.scan.outputs.verdict }}" = "WARN" ]; then
          echo "::warning::Workflow Guardian: Security issues detected, review recommended"
        fi
