AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  GENESIS 2.0 Security Infrastructure
  Enterprise-grade security orchestration using AWS Step Functions

Parameters:
  Environment:
    Type: String
    Default: production
    AllowedValues:
      - development
      - staging
      - production
    Description: Deployment environment

  AlertEmail:
    Type: String
    Description: Email address for security alerts

  SlackWebhookUrl:
    Type: String
    Default: ""
    Description: Slack webhook URL for notifications

Globals:
  Function:
    Runtime: nodejs20.x
    Timeout: 30
    MemorySize: 256
    Environment:
      Variables:
        ENVIRONMENT: !Ref Environment
        LOG_LEVEL: INFO

Resources:
  # ============================================================================
  # SNS Topics for Notifications
  # ============================================================================

  SecurityAlertsTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub genesis-security-alerts-${Environment}
      DisplayName: GENESIS Security Alerts
      KmsMasterKeyId: alias/aws/sns

  SecurityAlertsSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref SecurityAlertsTopic
      Protocol: email
      Endpoint: !Ref AlertEmail

  UserNotificationsTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub genesis-user-notifications-${Environment}
      DisplayName: GENESIS User Notifications

  # ============================================================================
  # SQS Queues for Async Processing
  # ============================================================================

  MFAResponseQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub genesis-mfa-responses-${Environment}
      VisibilityTimeout: 360
      MessageRetentionPeriod: 86400
      KmsMasterKeyId: alias/aws/sqs

  HumanTaskQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub genesis-human-tasks-${Environment}
      VisibilityTimeout: 86500
      MessageRetentionPeriod: 1209600
      KmsMasterKeyId: alias/aws/sqs

  SecurityEventsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub genesis-security-events-${Environment}
      VisibilityTimeout: 300
      KmsMasterKeyId: alias/aws/sqs
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt SecurityEventsDLQ.Arn
        maxReceiveCount: 3

  SecurityEventsDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub genesis-security-events-dlq-${Environment}
      MessageRetentionPeriod: 1209600

  # ============================================================================
  # S3 Bucket for Incident Reports
  # ============================================================================

  IncidentReportsBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Sub genesis-incident-reports-${AWS::AccountId}-${Environment}
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: aws:kms
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: ArchiveOldReports
            Status: Enabled
            Transitions:
              - StorageClass: GLACIER
                TransitionInDays: 90
            NoncurrentVersionExpiration:
              NoncurrentDays: 365

  # ============================================================================
  # DynamoDB Tables
  # ============================================================================

  SecurityEventsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub genesis-security-events-${Environment}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: eventId
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: S
        - AttributeName: category
          AttributeType: S
      KeySchema:
        - AttributeName: eventId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: category-timestamp-index
          KeySchema:
            - AttributeName: category
              KeyType: HASH
            - AttributeName: timestamp
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      SSESpecification:
        SSEEnabled: true

  IncidentsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub genesis-incidents-${Environment}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: incidentId
          AttributeType: S
        - AttributeName: status
          AttributeType: S
        - AttributeName: createdAt
          AttributeType: S
      KeySchema:
        - AttributeName: incidentId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: status-createdAt-index
          KeySchema:
            - AttributeName: status
              KeyType: HASH
            - AttributeName: createdAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      SSESpecification:
        SSEEnabled: true

  # ============================================================================
  # IAM Role for Step Functions
  # ============================================================================

  StepFunctionsExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub genesis-stepfunctions-role-${Environment}
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: states.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: StepFunctionsExecutionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:genesis-*
              - Effect: Allow
                Action:
                  - sns:Publish
                Resource:
                  - !Ref SecurityAlertsTopic
                  - !Ref UserNotificationsTopic
              - Effect: Allow
                Action:
                  - sqs:SendMessage
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                Resource:
                  - !GetAtt MFAResponseQueue.Arn
                  - !GetAtt HumanTaskQueue.Arn
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                Resource: !Sub ${IncidentReportsBucket.Arn}/*
              - Effect: Allow
                Action:
                  - states:StartExecution
                Resource: !Sub arn:aws:states:${AWS::Region}:${AWS::AccountId}:stateMachine:genesis-*
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:GetItem
                  - dynamodb:UpdateItem
                  - dynamodb:Query
                Resource:
                  - !GetAtt SecurityEventsTable.Arn
                  - !GetAtt IncidentsTable.Arn
                  - !Sub ${SecurityEventsTable.Arn}/index/*
                  - !Sub ${IncidentsTable.Arn}/index/*
              - Effect: Allow
                Action:
                  - logs:CreateLogDelivery
                  - logs:GetLogDelivery
                  - logs:UpdateLogDelivery
                  - logs:DeleteLogDelivery
                  - logs:ListLogDeliveries
                  - logs:PutResourcePolicy
                  - logs:DescribeResourcePolicies
                  - logs:DescribeLogGroups
                Resource: '*'

  # ============================================================================
  # Step Functions State Machines
  # ============================================================================

  SecurityOrchestratorStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Name: !Sub genesis-security-orchestrator-${Environment}
      DefinitionUri: step-functions/security-orchestrator.json
      DefinitionSubstitutions:
        AWS::Region: !Ref AWS::Region
        AWS::AccountId: !Ref AWS::AccountId
      Role: !GetAtt StepFunctionsExecutionRole.Arn
      Tracing:
        Enabled: true
      Logging:
        Level: ALL
        IncludeExecutionData: true
        Destinations:
          - CloudWatchLogsLogGroup:
              LogGroupArn: !GetAtt SecurityOrchestratorLogGroup.Arn
      Events:
        SecurityEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt SecurityEventsQueue.Arn
            BatchSize: 1

  EmergencyPlaybookStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Name: !Sub genesis-emergency-playbook-${Environment}
      DefinitionUri: step-functions/emergency-playbook.json
      DefinitionSubstitutions:
        AWS::Region: !Ref AWS::Region
        AWS::AccountId: !Ref AWS::AccountId
      Role: !GetAtt StepFunctionsExecutionRole.Arn
      Tracing:
        Enabled: true
      Logging:
        Level: ALL
        IncludeExecutionData: true
        Destinations:
          - CloudWatchLogsLogGroup:
              LogGroupArn: !GetAtt EmergencyPlaybookLogGroup.Arn

  ComplianceProcessorStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Name: !Sub genesis-compliance-processor-${Environment}
      DefinitionUri: step-functions/compliance-processor.json
      DefinitionSubstitutions:
        AWS::Region: !Ref AWS::Region
        AWS::AccountId: !Ref AWS::AccountId
      Role: !GetAtt StepFunctionsExecutionRole.Arn
      Tracing:
        Enabled: true
      Logging:
        Level: ALL
        IncludeExecutionData: true
        Destinations:
          - CloudWatchLogsLogGroup:
              LogGroupArn: !GetAtt ComplianceLogGroup.Arn

  # ============================================================================
  # CloudWatch Log Groups
  # ============================================================================

  SecurityOrchestratorLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/stepfunctions/genesis-security-orchestrator-${Environment}
      RetentionInDays: 90

  EmergencyPlaybookLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/stepfunctions/genesis-emergency-playbook-${Environment}
      RetentionInDays: 365

  ComplianceLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/stepfunctions/genesis-compliance-${Environment}
      RetentionInDays: 2555  # 7 years for compliance

  # ============================================================================
  # Lambda Functions (Stubs - implement business logic)
  # ============================================================================

  ClassifyEventFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub genesis-classify-event-${Environment}
      Handler: handlers/classify.handler
      CodeUri: ./src
      Description: Classify incoming security events
      Environment:
        Variables:
          EVENTS_TABLE: !Ref SecurityEventsTable

  ThreatIntelligenceFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub genesis-threat-intelligence-${Environment}
      Handler: handlers/threat-intel.handler
      CodeUri: ./src
      Description: Analyze threat indicators
      Timeout: 60

  RemediateFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub genesis-remediate-${Environment}
      Handler: handlers/remediate.handler
      CodeUri: ./src
      Description: Execute automated remediation actions
      Timeout: 120

  AuditLogFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub genesis-audit-log-${Environment}
      Handler: handlers/audit.handler
      CodeUri: ./src
      Description: Write audit log entries
      Environment:
        Variables:
          EVENTS_TABLE: !Ref SecurityEventsTable

  # ============================================================================
  # CloudWatch Alarms
  # ============================================================================

  HighSeverityEventsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub genesis-high-severity-events-${Environment}
      AlarmDescription: Alert when high severity security events spike
      MetricName: ExecutionsStarted
      Namespace: AWS/States
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 10
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: StateMachineArn
          Value: !Ref SecurityOrchestratorStateMachine
      AlarmActions:
        - !Ref SecurityAlertsTopic

  ExecutionFailuresAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub genesis-execution-failures-${Environment}
      AlarmDescription: Alert when state machine executions fail
      MetricName: ExecutionsFailed
      Namespace: AWS/States
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: StateMachineArn
          Value: !Ref SecurityOrchestratorStateMachine
      AlarmActions:
        - !Ref SecurityAlertsTopic

  DLQMessagesAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub genesis-dlq-messages-${Environment}
      AlarmDescription: Alert when messages land in DLQ
      MetricName: ApproximateNumberOfMessagesVisible
      Namespace: AWS/SQS
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: QueueName
          Value: !GetAtt SecurityEventsDLQ.QueueName
      AlarmActions:
        - !Ref SecurityAlertsTopic

Outputs:
  SecurityOrchestratorArn:
    Description: ARN of the Security Orchestrator State Machine
    Value: !Ref SecurityOrchestratorStateMachine
    Export:
      Name: !Sub ${AWS::StackName}-SecurityOrchestratorArn

  EmergencyPlaybookArn:
    Description: ARN of the Emergency Playbook State Machine
    Value: !Ref EmergencyPlaybookStateMachine
    Export:
      Name: !Sub ${AWS::StackName}-EmergencyPlaybookArn

  ComplianceProcessorArn:
    Description: ARN of the Compliance Processor State Machine
    Value: !Ref ComplianceProcessorStateMachine
    Export:
      Name: !Sub ${AWS::StackName}-ComplianceProcessorArn

  SecurityEventsQueueUrl:
    Description: URL of the Security Events Queue
    Value: !Ref SecurityEventsQueue
    Export:
      Name: !Sub ${AWS::StackName}-SecurityEventsQueueUrl

  IncidentReportsBucketName:
    Description: Name of the Incident Reports S3 Bucket
    Value: !Ref IncidentReportsBucket
    Export:
      Name: !Sub ${AWS::StackName}-IncidentReportsBucket

  SecurityAlertsTopicArn:
    Description: ARN of the Security Alerts SNS Topic
    Value: !Ref SecurityAlertsTopic
    Export:
      Name: !Sub ${AWS::StackName}-SecurityAlertsTopicArn
