#!/usr/bin/env python3
"""
CERT-MASTER Governance Report

Usage:
  python3 governance/cert_governance_report.py output/meta/CERT-XYZ.json
"""

import sys
import json
from pathlib import Path

ROOT_DIR = Path(__file__).resolve().parent.parent
CHARTER_DIR = ROOT_DIR / "charter"
GOV_DIR = ROOT_DIR / "governance"


def load_charter_meta():
    meta_path = CHARTER_DIR / "charter.meta.json"
    return json.load(meta_path.open(encoding="utf-8"))


def load_tombs():
    tombs_path = GOV_DIR / "tombs.log"
    if not tombs_path.exists():
        return []
    entries = []
    with tombs_path.open(encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            parts = line.split(" ", 4)
            if len(parts) >= 5:
                ts, sha, art_id, owner, reason = parts
                entries.append({
                    "timestamp": ts,
                    "sha256": sha,
                    "artifact_id": art_id,
                    "owner": owner,
                    "reason": reason
                })
    return entries


def main(meta_path_str: str) -> None:
    cert_meta_path = Path(meta_path_str)
    if not cert_meta_path.exists():
        print(f"ERROR: cert metadata not found: {cert_meta_path}", file=sys.stderr)
        sys.exit(1)

    cert_meta = json.load(cert_meta_path.open(encoding="utf-8"))
    charter_meta = load_charter_meta()
    tombs = load_tombs()

    cert_id = cert_meta.get("certificate_id", "<unknown>")
    charter_version = cert_meta.get("charter_version")
    charter_sha = cert_meta.get("charter_sha256")
    cli_sha = cert_meta.get("cert_master_cli_sha256")
    cli_art_id = cert_meta.get("cli_artifact_id", "<unknown>")

    print(f"=== CERT GOVERNANCE REPORT: {cert_id} ===\n")

    print("Charter Status:")
    print(f"  Recorded in cert: version={charter_version}, sha={charter_sha}")
    print(f"  Current repo:     version={charter_meta.get('version')}, sha={charter_meta.get('charter_sha256')}")
    if charter_sha == charter_meta.get("charter_sha256"):
        print("  ✓ OK: cert bound to current Charter")
    else:
        print("  ⚠ DIVERGED: cert bound to different Charter state")
    print()

    print("CERT-MASTER CLI Status:")
    print(f"  CLI artifact id: {cli_art_id}")
    print(f"  CLI sha256:      {cli_sha}")

    exiled = [e for e in tombs if e["sha256"] == cli_sha]
    if exiled:
        e = exiled[-1]
        print("  ⚰️ EXILED (Silver_Bullet)")
        print(f"    Exiled at:  {e['timestamp']}")
        print(f"    Owner:      {e['owner']}")
        print(f"    Reason:     {e['reason']}")
        print()
        print("⚠️  WARNING: This certificate was generated by an exiled CLI version")
    else:
        print("  ✓ NOT EXILED: CLI version is currently allowed")
    print()


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: cert_governance_report.py path/to/cert_meta.json", file=sys.stderr)
        sys.exit(1)
    main(sys.argv[1])
